### ISSUE TITLE
New files always set the print margin to 120, even though 80 is my preference

### ISSUE THREAD

**Issue by stowball** [Hirse/brackets-print-margin#4] opened 2015-02-17 22:55 UTC
I would have thought that it would set it to 80 on opening any file, but I have to manually click in to Print Margin in the status bar and press enter to trigger the 80 character margin.

**Comment by Hirse** [comment] 2015-02-18 08:37
Yes, that was the intended behaviour, but I forgot to listen to the `activeEditorChange` event.
I set 120 to be the default and fallback, so I didn't notice this bug as I only use that.

Should be fixed in v0.1.2

**Closed as completed by Hirse** 2015-02-18 08:37 UTC
Labels: bug

**Comment by stowball** [comment] 2015-02-18 09:22
Yep, works as expected! Thanks
